### ISSUE TITLE
Cannot complete the project in Chapter 10

### ISSUE THREAD

**Issue by bdeva1975** [PacktPublishing/Web-App-Development-Made-Simple-with-Streamlit#3]
For the model Covid19_CNN_Classifier.h5, I am getting an error constantly:-

ValueError: Kernel shape must have the same length as input, but received kernel of shape (3, 3, 1, 32) and input of shape (None, None, 200, 200, 1).

Kindly help me to complete the project.

**Comment by rosariomoscato** [comment]
Hello, you need to reshape the input as suggested by the error description.  Cheers

**Comment by github-dongpyo** [comment]
Hi, 

I do have the same issue. How can I fix it within code. Can you elaborate it?

**Comment by github-dongpyo** [comment]
> For the model Covid19_CNN_Classifier.h5, I am getting an error constantly:-
> 
> ValueError: Kernel shape must have the same length as input, but received kernel of shape (3, 3, 1, 32) and input of shape (None, None, 200, 200, 1).
> 
> Kindly help me to complete the project.

Hi, 

Did you find the solution? Where and how should I modify in the source code?
Could you share the solution?

**Comment by bdschaap** [comment]
> Hello, you need to reshape the input as suggested by the error description. Cheers

I'm running into the same error and have tried a number of things to resolve.  I believe it's on the line of code shown below.  Any help would be much appreciated.  Python 3.11, Tensorflow 2.13.0.

`model = tf.keras.models.load_model("./models/Covid19_CNN_Classifier.h5")`
